# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.5

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/dupuis/Dev/cpp/AUTOCAR_CMake

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/dupuis/Dev/cpp/AUTOCAR_CMake

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/cmake-gui -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/dupuis/Dev/cpp/AUTOCAR_CMake/CMakeFiles /home/dupuis/Dev/cpp/AUTOCAR_CMake/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/dupuis/Dev/cpp/AUTOCAR_CMake/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named mcastEchoServer

# Build rule for target.
mcastEchoServer: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 mcastEchoServer
.PHONY : mcastEchoServer

# fast build rule for target.
mcastEchoServer/fast:
	$(MAKE) -f CMakeFiles/mcastEchoServer.dir/build.make CMakeFiles/mcastEchoServer.dir/build
.PHONY : mcastEchoServer/fast

#=============================================================================
# Target rules for targets named mcastSend

# Build rule for target.
mcastSend: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 mcastSend
.PHONY : mcastSend

# fast build rule for target.
mcastSend/fast:
	$(MAKE) -f CMakeFiles/mcastSend.dir/build.make CMakeFiles/mcastSend.dir/build
.PHONY : mcastSend/fast

src/mcastEchoServer.o: src/mcastEchoServer.cpp.o

.PHONY : src/mcastEchoServer.o

# target to build an object file
src/mcastEchoServer.cpp.o:
	$(MAKE) -f CMakeFiles/mcastEchoServer.dir/build.make CMakeFiles/mcastEchoServer.dir/src/mcastEchoServer.cpp.o
.PHONY : src/mcastEchoServer.cpp.o

src/mcastEchoServer.i: src/mcastEchoServer.cpp.i

.PHONY : src/mcastEchoServer.i

# target to preprocess a source file
src/mcastEchoServer.cpp.i:
	$(MAKE) -f CMakeFiles/mcastEchoServer.dir/build.make CMakeFiles/mcastEchoServer.dir/src/mcastEchoServer.cpp.i
.PHONY : src/mcastEchoServer.cpp.i

src/mcastEchoServer.s: src/mcastEchoServer.cpp.s

.PHONY : src/mcastEchoServer.s

# target to generate assembly for a file
src/mcastEchoServer.cpp.s:
	$(MAKE) -f CMakeFiles/mcastEchoServer.dir/build.make CMakeFiles/mcastEchoServer.dir/src/mcastEchoServer.cpp.s
.PHONY : src/mcastEchoServer.cpp.s

src/mcastSend.o: src/mcastSend.cpp.o

.PHONY : src/mcastSend.o

# target to build an object file
src/mcastSend.cpp.o:
	$(MAKE) -f CMakeFiles/mcastSend.dir/build.make CMakeFiles/mcastSend.dir/src/mcastSend.cpp.o
.PHONY : src/mcastSend.cpp.o

src/mcastSend.i: src/mcastSend.cpp.i

.PHONY : src/mcastSend.i

# target to preprocess a source file
src/mcastSend.cpp.i:
	$(MAKE) -f CMakeFiles/mcastSend.dir/build.make CMakeFiles/mcastSend.dir/src/mcastSend.cpp.i
.PHONY : src/mcastSend.cpp.i

src/mcastSend.s: src/mcastSend.cpp.s

.PHONY : src/mcastSend.s

# target to generate assembly for a file
src/mcastSend.cpp.s:
	$(MAKE) -f CMakeFiles/mcastSend.dir/build.make CMakeFiles/mcastSend.dir/src/mcastSend.cpp.s
.PHONY : src/mcastSend.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... mcastEchoServer"
	@echo "... mcastSend"
	@echo "... src/mcastEchoServer.o"
	@echo "... src/mcastEchoServer.i"
	@echo "... src/mcastEchoServer.s"
	@echo "... src/mcastSend.o"
	@echo "... src/mcastSend.i"
	@echo "... src/mcastSend.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

